name: AI CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov ruff docker

    - name: Lint with Ruff
      run: ruff check .

    - name: Run unit tests with coverage
      run: |
        pytest --cov=. --cov-fail-under=80 tests/unit/

    - name: Run integration tests
      run: |
        pytest tests/integration/
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    - name: Build Docker image
      run: |
        docker build -t ai-cicd:latest .

    - name: Run container tests
      run: |
        docker run --rm ai-cicd:latest pytest tests/container/
