version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_BACKEND_STORE_URI=/mlflow/mlruns
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0 --port 5000

  fastapi-app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_MODEL_NAME=sentiment_classifier
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mlflow
