name: Monorepo CI Dispatcher

on:
  pull_request:
    paths:
      - 'projects/**'
  push:
    branches: [main]

jobs:
  find-projects:
    runs-on: ubuntu-latest
    outputs:
      project-list: ${{ steps.projects.outputs.project-list }}
    steps:
      - uses: actions/checkout@v4

      - name: List all project ci.yaml files
        id: projects
        run: |
          echo "Searching for changed projects with ci.yaml..."
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^projects/' | cut -d/ -f2-3 | uniq || true)

          json_array="["
          first=true
          for dir in $changed; do
            if [ -f "projects/$dir/ci.yaml" ]; then
              if [ "$first" = true ]; then
                first=false
              else
                json_array+=","
              fi
              json_array+="\"$dir\""
            fi
          done
          json_array+="]"

          echo "Final matrix: $json_array"
          echo "project-list=$json_array" >> $GITHUB_OUTPUT

      - name: Check if project-list is empty
        run: |
            if [ -z "${{ steps.projects.outputs.project-list }}" ]; then
            echo "No projects found, exiting with success"
            exit 0
            fi

  matrix-ci:
    needs: find-projects
    if: ${{ needs.find-projects.outputs.project-list != '[]' }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.find-projects.outputs.project-list) }}

    uses: ./.github/workflows/ci-runner.yml
    with:
      project: ${{ matrix.project }}
